#%RAML 1.0
---
title: Auth API
version: v1
baseUri: api.auth.com/{version}
schemas:
    Permission:
        properties:
            scope: string
            name: string
            description: string
    Role:
        properties:
            orgId: string
            name: string
            permissions: Permission[]
    Organization:
        properties:
            name: string
            roles: RoleAPI[] | Role[] | string[]
            users: UserAPI[] | User[] | string[]
    User:
        properties:
            uniqueId: string
            firstname: string
            lastname: string
            email: string
            organizations: OrganizationAPI[] | Organization[] | string[]
            roles: RoleAPI[] | Role[] | string[]
    RoleAPI:
        properties:
            data: Role
            links:
                properties:
                    org: string
                    self: string
    OrganizationAPI:
        properties:
            data: Organization
            links: 
                properties:
                    self: string
                    roles: string
                    users: string
    UserAPI:
        properties:
            data: User
            links:
                properties:
                    self: string
    
/login:
    post:
        description: |
        headers: 
        body: 
            application/json:
                properties:
                    id_token: string
                    id_provider: string
        responses: 
            200:
                body:
                    application/json:
                        access_token: string
            400:
/register:
    post:
        description: |
        headers: 
        body: 
            application/json:
                properties:
                    id_token: string
                    id_provider: string
        responses: 
            200:
                body:
                    application/json:
                        access_token: string
            400:
/organizations:
    post:
        description: Allows to create a new organization |
        headers: 
        body: 
            application/json:
                properties:
                    name: string
        responses: 
            200:
                body:
                    application/json:
                        type: OrganizationAPI
            400:
    /{orgId}: 
        get:
            description: Allows to retrieve the organization |
            headers: 
            responses: 
                200:
                    body:
                        application/json:
                            type: OrganizationAPI
                400:
                404:
        /roles:
            post:
                description: |
                headers: 
                body: 
                    type: Role
                responses: 
                    200:
                        body:
                            application/json:
                                type: RoleAPI
                    400:
                    404:
            get:
                description: Allows to retrieve the organization roles |
                headers: 
                responses: 
                    200:
                        body:
                            application/json:
                                type: RoleAPI[]
                    404:
            /{roleId}: 
                put:
                    description: Allows to modify the role name and its permissions |
                    headers: 
                    body: 
                    responses: 
                        200:
                            body:
                                application/json:
                                    type: RoleAPI
                        400:
                        404:
                get:
                    description: Allows to get the role |
                    headers: 
                    responses: 
                        200:
                            body:
                                application/json:
                                    type: RoleAPI
                        400:
                        404:
                delete:
                    description: Allows to remove the role from the organization |
                    headers: 
                    responses: 
                        200:
                        400:
                        404:
        /users:
            post:
                description: Allows to assign an user to the organization |
                headers: 
                body: 
                    application/json:
                        properties:
                            userId: string
                responses: 
                    200:
                        body:
                            application/json:
                                type: UserAPI[]
                    400:
                    404:
            get:
                description: Allows to retieve the users beloging to the organization |
                headers: 
                responses:
                    200:
                        body:
                            application/json:
                                type: UserAPI[]
                    400:
                    404:
            /{userId}:
                delete:
                    description: Allows to remove the user from the organization |
                    headers: 
                    responses: 
                        200:
                        400:
                        404:
                /roles: 
                    post:
                        description: Allows to assign a role to the user |
                        headers: 
                        body: 
                            application/json:
                                properties:
                                    rolesIds: string[]
                        responses: 
                            200:
                            400:
                            404:
                    get:
                        description: Allows to retrieve the user's roles |
                        headers: 
                        responses: 
                            200:
                                body:
                                    application/json:
                                        type: RoleAPI[]
                            400:
                            404:
                    /{roleId}: 
                        delete:
                            description: Allows to remove a role from the user |
                            headers: 
                            responses: 
                                200:
                                400:
                                404:
/users/{userId}: 
    get:
        description: Allows to retrieve user informations |
        headers: 
        body: 
        responses: 
            200:
                body:
                    application/json:
                        type: UserAPI
            400:
            404:
    /roles:
        get:
            description: Allows to retrieve user's roles |
            headers: 
            body: 
            responses: 
                200:
                    body:
                        application/json:
                            type: RoleAPI[]
                400:
                404:
    /organizations:
        get:
            description: Allows to retrieve user's organizations |
            headers: 
            body: 
            responses: 
                200:
                    body:
                        application/json:
                            type: OrganizationAPI[]
                400:
                404:
